name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy to FLwolfy.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_DEPLOY_TOKEN }}
          publish_dir: ./public
          repository: FLwolfy/FLwolfy.github.io
          publish_branch: main
          user_name: Hsuan-Kai Liao
          user_email: hsuankailiao@gmail.com
