name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Clean old files
        run: npx hexo clean

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_DEPLOY_TOKEN }}    # 请替换成你的 GitHub Secret Token 名称
          external_repository: YourName/YourName.github.io  # 请替换成你的 GitHub Pages 仓库地址
          publish_dir: ./public
          publish_branch: main
          keep_files: false
          user_name: YourName                  # 请替换成你的 GitHub 用户名            
          user_email: YourEmail@youremail.com  # 请替换成你的 GitHub 邮箱
